### ISSUE TITLE
What is the meaning of UDP ping?

### ISSUE THREAD

**Issue by nifflin** [tobgu/pingo#1]
Isn't ICMP ping not enough? In what scenario does the UDP ping works better than ICMP ping?

**Comment by tobgu** [comment]
Sure, for many cases it is, but it also more low level and usually handled by the OS.

The UDP ping measures more or less the same properties of the network that a ICMP ping would do but using a protocol that is more commonly used for applications (which is the intent of pingo, to measure network performance using application-like traffic).

Also there may be restrictions on if/how ICMP can be used in networks and on hosts or special treatment of ICMP in other ways that you can also get around using UDP.

I also have some plans on supporting asymmetrical payload sizes (eg. where the send size and receive size differ) as well as some checksums and stuff. I think this should be easier using UDP since it would be a lot trickier to build an ICMP server.

As a final motivation it is also slightly easier to implement using UDP.
